language: ruby
cache: bundler
rvm:
  - 2.1.5
  - 2.2.2
  - rbx
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
matrix:
  fast_finish: true
addons:
  postgresql: "9.4"
env:
  - DB=sqlite3
  - DB=postgresql
script:
    - bundle exec rspec
before_script:
    - gem update bundler
    - psql -c 'create database propertybase_id_test;' -U postgres
